spring:
  application:
    name: bitcoin-api
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/bitcoindb?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: secret
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:29092}
      bindings:
        prices-out-0:
          destination: com.ivanfranchin.bitcoin.api.price

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
