spring:
  application:
    name: bitcoin-client
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:29092}
      bindings:
        prices-in-0:
          destination: com.ivanfranchin.bitcoin.api.price
          group: bitcoinClientGroup
